# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-29 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20180429_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono_local',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono_movil',
            field=models.CharField(max_length=50),
        ),
    ]
